---
- name: SSH_key
  user:
    name: vagrant
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
- name: Add authorizedid_rsa.pub
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"
